
Vagrant.configure("2") do |config|

  config.vm.box = "jasonc/centos7"
  
  ### Single VM
  config.vm.hostname = "testbox01"
  config.vm.network "private_network", ip: "192.168.56.21"

  ### Multiple VMs
  # config.vm.define "test1" do |test1|
  #   test1.vm.hostname = "test1"
  #   test1.vm.network "private_network", ip: "192.168.56.7"
  # end
  # config.vm.define "test2" do |test2|
  #   test2.vm.hostname = "test2"
  #   test2.vm.network "private_network", ip: "192.168.56.8"
  # end

end
